Onedrop:
  Form:
    Hubspot:
      api:
        hapikey: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        portalId: xxxxxxx
      finishers:
        - identifier: Onedrop.Form.Hubspot:HubSpotFinisher
          options: []
  AjaxForm:
    includeJavascript: true
Neos:
  Neos:
    fusion:
      autoInclude:
        Onedrop.Form.Hubspot: true
