Onedrop:
  Form:
    Hubspot:
      api:
        hapikey: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        portalId: xxxxxxx
      recaptcha_v2:
        sitekey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        secretkey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        enableRecaptcha: false

      finishers:
        - identifier: Onedrop.Form.Hubspot:HubSpotFinisher
          options: []
  AjaxForm:
    includeJavascript: true
Neos:
  Neos:
    fusion:
      autoInclude:
        Onedrop.Form.Hubspot: true

  AjaxForm:
    includeJavascript: true
  Flow:
    mvc:
      routes:
        'Onedrop.Form.Hubspot':
          position: 'start'
