Onedrop:
  Form:
    Hubspot:
      api:
        hapikey: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        portalId: xxxxxxx
      finishers:
        - identifier: Onedrop.Form.Hubspot:HubSpotFinisher
          options: []
Neos:
  Neos:
    fusion:
      autoInclude:
        Onedrop.Form.Hubspot: true
  Form:
    presets:
      default:
        finisherPresets:
          'Onedrop.Form.Hubspot:HubSpotFinisher':
            implementationClassName: 'Onedrop\Form\Hubspot\Form\Finisher\HubSpotFinisher'
