Onedrop:
  Neos:
    Hubspot:
      api:
        hapikey: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Neos:
  Neos:
    fusion:
      autoInclude:
        Onedrop.Neos.Hubspot: true
  Form:
    presets:
      default:
        finisherPresets:
          'Onedrop.Neos.Hubspot:HubSpotFinisher':
            implementationClassName: 'Onedrop\Neos\Hubspot\Form\Finisher\HubSpotFinisher'
