Onedrop:
  Form:
    Hubspot:
      api:
        hapikey: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Neos:
  Neos:
    fusion:
      autoInclude:
        Onedrop.Form.Hubspot: true
  Form:
    presets:
      default:
        finisherPresets:
          'Onedrop.Form.Hubspot:HubSpotFinisher':
            implementationClassName: 'Onedrop\Form\Hubspot\Form\Finisher\HubSpotFinisher'
